config/routes.rb
Rails.application.routes.draw do
  resources :pins

  root 'pins#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/pin.rb
class Pin < ApplicationRecord
   mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_category_nav

  private
    def get_category_nav
      @images = Pin.all
    end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :find_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all.order('created_at DESC')
  end

  def show
  	
  end

  def new
  	@image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to @image, notice: 'Success'    	
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Success'
    else
      render 'edit'
    end
  end

  def destroy
    @image.destroy
    redirect_to root_path
  end

  private
    
    def image_params
      params.require(:image).permit(:title, :description)
    end

    def find_image
      @image = Image.find(params[:id])
    end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Pin.all.order('created_at DESC')
  end

  def show
  	
  end

  def new
  	@image = Pin.new
  end

  def create
    @image = Pin.new(image_params)

    if @image.save
      redirect_to @image, notice: 'Success'    	
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @image.update(image_params)
      redirect_to @image, notice: 'Success'
    else
      render 'edit'
    end
  end

  def destroy
    @image.destroy
    redirect_to root_path
  end

  private
    
    def image_params
      params.require(:pin).permit(:title, :description, :image)
    end

    def find_image
      @image = Pin.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/images/edit.html.haml
%h1 Edit image
= form_for @image, :html => {:multipart => true} do |f|
  = image_tag @image.ipath.url(:thumb), class:'img-fluid rounded'
  %br
  .form-group
    = f.label :ipath
    = f.file_field :ipath, class:'form-control'
  .form-group
    = f.label :image_title
    = f.text_area :image_description, class:'form-control'
  .form-group
    = f.submit 'submit', class:'btn btn-light'
    = link_to 'cancel', image_path, class:'btn btn-light'

= link_to 'Cancel', image_path

app/views/images/index.html.haml
%h1 all Imges
= link_to 'New image', new_image_path
- @images.each do |image|
  %h2= link_to image.title, image

app/views/images/new.html.haml
%h1 Upload Image
= form_for @image, :html => {:multipart => true} do |f|
  - if @image.errors.any?
    - @image.errors.full_messages.each do |msg|
      .alert.alert-danger= msg
  .form-group
    = f.label :title
    = f.text_field :title, class:'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class:'form-control'
  .form-group
    = f.label :ipath
    = f.file_field :ipath

  = f.submit 'Submit', class:'btn btn-light'
  / = link_to 'Cancel', images_path, class:'btn btn-light'
  = link_to 'Back', root_path

app/views/images/show.html.haml
%h1= @image.title
%p= @image.description
/ # = image_tag @image.ipath.url(:thumb)

= link_to 'Back', root_path
= link_to 'Edit', edit_image_path
= link_to 'Delete', image_path, method: :delete, data: { confirm: 'Are u sure?' }

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Iboard
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %nav.navbar.navbar-expand-md.navbar-light.bg-light
      %ul.navbar-nav
        %a.navbar-brand{ href: "/"} Gallery
        %li.nav-item.dropdown
          %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "true", href: root_path, "aria-haspopup" => "true", "data-toggle" => "dropdown"}
            = 'Gallery'
          .dropdown-menu
            = link_to 'Images', pins_path, class: 'nav-link'
            .dropdown-divider
            - @images.each do |image|
              %a.dropdown-item{ href: pin_path(image.id)} 
                = image.title
       


    - flash.each do |name, msg|
      = content_tag :div, msg, class: 'alert alert_info'
    = yield

app/views/pins/edit.html.haml
%h1 Edit image
= form_for @image, :html => {:multipart => true} do |f|
  / = image_tag @image.image.url, class:'img-fluid rounded'
  %br
  .form-group
    = f.label :image
    = f.file_field :image, class:'form-control'
  .form-group
    = f.label :title
    = f.text_area :description, class:'form-control'
  .form-group
    = f.submit 'submit', class:'btn btn-light'
    = link_to 'cancel', pin_path, class:'btn btn-light'

app/views/pins/index.html.haml
#pins.transitions-enabled
  - @images.each do |image|
    .box.panel.panel-default
      %h2= link_to image.title, image
      = image_tag image.image.url
      = link_to 'Edit', edit_pin_path(image.id)
      = link_to 'Delete', pin_path(image.id), method: :delete, data: { confirm: 'Are u sure?' }
      = link_to 'New image', new_pin_path

app/views/pins/new.html.haml
%h1 Upload Image
= form_for @image, :html => {:multipart => true} do |f|
  - if @image.errors.any?
    - @image.errors.full_messages.each do |msg|
      .alert.alert-danger= msg
  .form-group
    = f.label :title
    = f.text_field :title, class:'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class:'form-control'
  .form-group
    = f.label :image
    = f.file_field :image

  = f.submit 'Submit', class:'btn btn-light'
  / = link_to 'Cancel', images_path, class:'btn btn-light'
  = link_to 'Back', root_path

app/views/pins/show.html.haml
%h1= @image.title
%p= @image.description
= image_tag @image.image.url

= link_to 'Back', root_path
= link_to 'Edit', edit_pin_path
= link_to 'Delete', pin_path, method: :delete, data: { confirm: 'Are u sure?' }